### PR TITLE
Update copyright year logic

### PR DESCRIPTION
**Pull request by rootial**
See as title

## Test 

test locally
image

## Reviewers
@mhluongo @henryboldi @Shadowfiend

### CODE REVIEW

**Comment by rootial** [comment]
Hi guys, can i get a stamp ? @mhluongo @henryboldi @Shadowfiend

**Review by mhluongo — APPROVED** [review]
LGTM, thank you and happy early New Year! 🥳🎊

**Comment by mhluongo** [comment]
Drat, I forgot about commit signing requirements. @rootial  if you have signing set up, can you force-push a branch of signed commits? If not I can vouch and sign these myself to get it on `main`

**Comment by rootial** [comment]
I have not setup sign, can you help on this ? thx @mhluongo

**Comment by henryboldi** [comment]
@rootial Here's a helpful video tutorial on signing commits! https://www.youtube.com/watch?v=4V-7KnhcrbY

The video essentially walks you through the written guide here https://github.com/pstadler/keybase-gpg-github

**Comment by mhluongo** [comment]
Signed myself and pushed to master ea30209ac70ff9f0bebdd6d3349726e7ac63ba2e. Thanks @rootial!

**Pull request closed without merging**
